package main

import (
	example "learn_go/go_by_example"
	recordsAPI "learn_go/records_api"
	validator "learn_go/validator"
)

func main() {
	// ---------------------
	// --- Records API -----
	// ---------------------
	recordsAPI.Init()
	// recordsAPI.Main()

	// ------------------------------
	// --- Validator Examples -------
	// ------------------------------
	validator.Init()
	// validator.Simple()
	// validator.CustomFieldTypes()
	// validator.StructLevel()
	// validator.TranslationsAndCustomErrors()

	// ---------------------
	// --- Go by Example ---
	// ---------------------
	example.Init()
	// example.HelloWorld()
	// example.Values()
	// example.Variables()
	// example.Constants()
	// example.For()
	// example.IfElse()
	// example.Switch()
	// example.Arrays()
	// example.Slices()
	// example.Maps()
	// example.Range()
	// example.Functions()
	// example.MultipleReturnValues()
	// example.VariadicFunctions()
	// example.Closures()
	// example.Recursion()
	// example.Pointers()
	// example.StringsAndRunes()
	// example.Structs()
	// example.Methods()
	// example.Interfaces()
	// example.Enums()
	// example.StructEmbedding()
	// example.Generics()
	// example.Errors()
	// example.CustomErrors()
	// example.Goroutines()
	// example.Channels()
	// example.ChannelBuffering()
	// example.ChannelSynchronization()
	// example.ChannelDirections()
	// example.Select()
	// example.Timeouts()
	// example.NonBlockingChannelOperations()
	// example.ClosingChannels()
	// example.RangeOverChannels()
	// example.Timers()
	// example.Tickers()
	// example.WorkerPools()
	// example.WaitGroups()
	// example.RateLimiting()
	// example.AtomicCounters()
	// example.Mutexes()
	// example.StatefulGoroutines()
	// example.Sorting()
	// example.SortingByFunctions()
	// example.Panic()
	// example.Defer()
	// example.Recover()
	// example.StringFunctions()
	// example.StringFormatting()
	// example.TextTemplates()
	// example.RegularExpressions()
	// example.JSON()
	// example.XML()
	// example.Time()
	// example.Epoch()
	// example.TimeFormattingParsing()
	// example.RandomNumbers()
	// example.NumberParsing()
	// example.URLParsing()
	// example.SHA256Hashes()
	// example.Base64Encoding()
	// example.ReadingFiles()
	// example.WritingFiles()
	// example.LineFilters()
	// example.FilePaths()
	// example.Directories()
	// example.TemporaryFilesAndDirectories()
	// example.EmbedDirective()
	// -- Testing and Benchmarking --- (ran with `go test -v ./...`)
	// example.CommandLineArguments()
	// example.CommandLineFlags()
	// example.CommandLineSubcommands()
	// example.EnvironmentVariables()
	// example.Logging()
	// example.HTTPClient()
	// example.HTTPServer()
	// example.Context()
	// example.SpawningProcesses()
	// example.ExecingProcesses()
	// example.Signals()
	// example.Exit()
}